'use client';
import {useEffect,useState} from 'react';
const cats=['Master CV','Reference Letter','Qualification / Transcript','Certificate / Licence','Supporting Document'];
export default function DocumentVaultBridge(){
 const[open,setOpen]=useState(false),[docs,setDocs]=useState([]),[category,setCategory]=useState(cats[0]),[file,setFile]=useState(null),[busy,setBusy]=useState(false),[msg,setMsg]=useState('');
 async function load(){const r=await fetch('/api/documents',{cache:'no-store'});const d=await r.json().catch(()=>({}));if(r.ok)setDocs(d.documents||[]);else setMsg(d.error||'Sign in to use the Document Vault')}
 useEffect(()=>{const h=e=>{const b=e.target.closest?.('button');if(b&&b.textContent?.trim()==='Documents'){setTimeout(()=>{setOpen(true);load()},0)}};document.addEventListener('click',h);return()=>document.removeEventListener('click',h)},[]);
 async function upload(){if(!file)return setMsg('Choose a file first');setBusy(true);setMsg('Uploading securely…');const f=new FormData();f.append('file',file);f.append('category',category);const r=await fetch('/api/documents',{method:'POST',body:f});const d=await r.json().catch(()=>({}));setBusy(false);if(!r.ok)return setMsg(d.error||'Upload failed');setFile(null);setMsg('Uploaded successfully');load()}
 async function download(id){setMsg('Preparing secure download…');const r=await fetch('/api/documents',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({id})});const d=await r.json().catch(()=>({}));if(r.ok&&d.url){window.open(d.url,'_blank','noopener,noreferrer');setMsg('Download ready')}else setMsg(d.error||'Download failed')}
 async function remove(id){if(!confirm('Delete this document permanently?'))return;const r=await fetch('/api/documents?id='+encodeURIComponent(id),{method:'DELETE'});const d=await r.json().catch(()=>({}));setMsg(r.ok?'Document deleted':d.error||'Delete failed');if(r.ok)load()}
 if(!open)return null;
 return <div style={{position:'fixed',inset:0,zIndex:9999,background:'#f5f7ff',overflow:'auto'}}><div style={{maxWidth:1100,margin:'0 auto',padding:'36px 24px 80px'}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:20}}><div><div style={{fontWeight:800,letterSpacing:3,color:'#5b43ed',fontSize:13}}>DOCUMENT VAULT</div><h1 style={{fontSize:46,margin:'10px 0'}}>Your reusable documents</h1><p style={{fontSize:18,color:'#586174'}}>Private files for CV tailoring and applications.</p></div><button onClick={()=>setOpen(false)} style={{fontSize:18,padding:'12px 20px',borderRadius:12,border:'1px solid #ccd2e3',background:'white'}}>← Back to ApplyAI</button></div>
 <div style={{background:'white',border:'1px solid #dce1ef',borderRadius:20,padding:26,marginTop:26,boxShadow:'0 8px 30px #23305b10'}}><h2>Upload a document</h2><p>PDF, DOC, DOCX, JPG or PNG · maximum 15 MB. Files are stored in private object storage.</p><div style={{display:'flex',gap:12,flexWrap:'wrap',alignItems:'center'}}><select value={category} onChange={e=>setCategory(e.target.value)} style={{padding:13,borderRadius:10,border:'1px solid #ccd2e3',fontSize:16}}>{cats.map(c=><option key={c}>{c}</option>)}</select><input type="file" accept=".pdf,.doc,.docx,.jpg,.jpeg,.png" onChange={e=>setFile(e.target.files?.[0]||null)} style={{padding:12,border:'1px solid #ccd2e3',borderRadius:10,flex:'1 1 300px'}}/><button disabled={busy} onClick={upload} style={{padding:'14px 24px',border:0,borderRadius:10,background:'#5b43ed',color:'white',fontWeight:800,fontSize:16}}>{busy?'Uploading…':'Upload securely'}</button></div>{msg&&<p style={{fontWeight:700,color:'#4d43a8'}}>{msg}</p>}</div>
 <div style={{marginTop:24}}><h2>Stored documents ({docs.length})</h2>{docs.length===0?<div style={{background:'white',padding:30,borderRadius:16,border:'1px dashed #c9cfdf'}}>No documents uploaded yet.</div>:docs.map(d=><div key={d.id} style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:15,background:'white',padding:18,marginBottom:10,border:'1px solid #e0e4ef',borderRadius:14,flexWrap:'wrap'}}><div><b style={{fontSize:17}}>{d.file_name}</b><div style={{color:'#687086',marginTop:5}}>{d.category} · {Math.max(1,Math.round(Number(d.size_bytes||0)/1024))} KB</div></div><div style={{display:'flex',gap:8}}><button onClick={()=>download(d.id)} style={{padding:'10px 16px',borderRadius:9,border:'1px solid #cbd1e1',background:'white',fontWeight:700}}>Download</button><button onClick={()=>remove(d.id)} style={{padding:'10px 16px',borderRadius:9,border:'1px solid #e2b7bd',background:'white',fontWeight:700}}>Delete</button></div></div>)}</div></div></div>
}