'use client';
import {useEffect,useState} from 'react';
const cats=['Master CV','Reference Letter','Qualification / Transcript','Certificate / Licence','Supporting Document'];
const btn={padding:'10px 14px',borderRadius:9,border:'1px solid #cbd1e1',background:'white',fontWeight:700,cursor:'pointer'};
export default function DocumentVaultBridge(){
 const[open,setOpen]=useState(false),[docs,setDocs]=useState([]),[generated,setGenerated]=useState([]),[category,setCategory]=useState(cats[0]),[file,setFile]=useState(null),[busy,setBusy]=useState(false),[msg,setMsg]=useState('');
 async function load(){const r=await fetch('/api/documents',{cache:'no-store'});const d=await r.json().catch(()=>({}));if(r.ok){setDocs(d.documents||[]);setGenerated(d.generated_documents||d.generated||[])}else setMsg(d.error||'Sign in to use the Document Vault')}
 useEffect(()=>{const h=e=>{const b=e.target.closest?.('button');if(b&&b.textContent?.trim()==='Documents'){setTimeout(()=>{setOpen(true);load()},0)}};document.addEventListener('click',h);return()=>document.removeEventListener('click',h)},[]);
 async function upload(){if(!file)return setMsg('Choose a file first');setBusy(true);setMsg('Uploading securely…');const f=new FormData();f.append('file',file);f.append('category',category);const r=await fetch('/api/documents',{method:'POST',body:f});const d=await r.json().catch(()=>({}));setBusy(false);if(!r.ok)return setMsg(d.error||'Upload failed');setFile(null);setMsg('Uploaded successfully');load()}
 async function download(id){setMsg('Preparing secure download…');const r=await fetch('/api/documents',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({id})});const d=await r.json().catch(()=>({}));if(r.ok&&d.url){window.open(d.url,'_blank','noopener,noreferrer');setMsg('Download ready')}else setMsg(d.error||'Download failed')}
 async function remove(id){if(!confirm('Delete this document permanently?'))return;const r=await fetch('/api/documents?id='+encodeURIComponent(id),{method:'DELETE'});const d=await r.json().catch(()=>({}));setMsg(r.ok?'Document deleted':d.error||'Delete failed');if(r.ok)load()}
 function generatedAction(d,action){const url=d?.[action+'_url']||d?.[action+'Url'];if(url)return window.open(url,'_blank','noopener,noreferrer');setMsg(action==='unlock'?'Clean download is unlocked after the $5 Application Pack or eligible Pro purchase.':'This document action will become available as soon as the application generator saves the document.')}
 if(!open)return null;
 return <div style={{position:'fixed',inset:0,zIndex:9999,background:'#f5f7ff',overflow:'auto'}}><div style={{maxWidth:1100,margin:'0 auto',padding:'36px 24px 80px'}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:20}}><div><div style={{fontWeight:800,letterSpacing:3,color:'#5b43ed',fontSize:13}}>DOCUMENT VAULT</div><h1 style={{fontSize:46,margin:'10px 0'}}>Your documents</h1><p style={{fontSize:18,color:'#586174'}}>Manage AI-generated and uploaded documents for your applications.</p></div><button onClick={()=>setOpen(false)} style={{fontSize:18,padding:'12px 20px',borderRadius:12,border:'1px solid #ccd2e3',background:'white'}}>← Back to ApplyAI</button></div>
 <section style={{background:'white',border:'1px solid #dce1ef',borderRadius:20,marginTop:26,overflow:'hidden',boxShadow:'0 8px 30px #23305b10'}}><div style={{padding:26,background:'linear-gradient(90deg,#f3f0ff,#f8fbff)'}}><h2 style={{margin:'0 0 6px'}}>✨ Generated Application Documents</h2><div style={{color:'#626b80'}}>Tailored to specific opportunities. Free versions include an ApplyAI watermark.</div></div><div style={{padding:24}}>{generated.length===0?<div style={{padding:26,border:'1px dashed #c9cfdf',borderRadius:14}}><b>No generated documents yet.</b><p style={{color:'#687086'}}>Choose a vacancy and click <b>Prepare Application</b>. Your tailored CV and cover letter will be saved here automatically.</p><button onClick={()=>setOpen(false)} style={{...btn,background:'#5b43ed',color:'white',border:0}}>Find an opportunity →</button></div>:<div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(360px,1fr))',gap:14}}>{generated.map((d,i)=><div key={d.id||i} style={{border:'1px solid #e0e4ef',borderRadius:15,padding:18}}><div style={{display:'flex',justifyContent:'space-between',gap:12}}><div><b style={{fontSize:20}}>{d.title||d.type||'Generated document'}</b><div style={{color:'#687086',marginTop:6}}>{d.job_title||d.opportunity_title||''}{(d.employer||d.organization)?' · '+(d.employer||d.organization):''}</div></div><span style={{height:'fit-content',padding:'5px 9px',borderRadius:20,background:'#edf7ff',color:'#2867b2',fontSize:12,fontWeight:800}}>{d.paid||d.watermark_removed?'Clean':'Free · Watermarked'}</span></div><div style={{display:'flex',gap:8,flexWrap:'wrap',marginTop:18}}><button style={btn} onClick={()=>generatedAction(d,'preview')}>Preview</button><button style={btn} onClick={()=>generatedAction(d,'edit')}>Edit</button><button style={btn} onClick={()=>generatedAction(d,'download')}>Download {d.paid||d.watermark_removed?'':'Watermarked'}</button>{!(d.paid||d.watermark_removed)&&<button style={{...btn,color:'#5b43ed',borderColor:'#bdb3ff'}} onClick={()=>generatedAction(d,'unlock')}>Remove Watermark · $5</button>}</div></div>)}</div>}</div></section>
 <div style={{background:'white',border:'1px solid #dce1ef',borderRadius:20,padding:26,marginTop:26,boxShadow:'0 8px 30px #23305b10'}}><h2>Upload a document</h2><p>Master CVs, reference letters, qualifications and supporting files. PDF, DOC, DOCX, JPG or PNG · maximum 15 MB.</p><div style={{display:'flex',gap:12,flexWrap:'wrap',alignItems:'center'}}><select value={category} onChange={e=>setCategory(e.target.value)} style={{padding:13,borderRadius:10,border:'1px solid #ccd2e3',fontSize:16}}>{cats.map(c=><option key={c}>{c}</option>)}</select><input type="file" accept=".pdf,.doc,.docx,.jpg,.jpeg,.png" onChange={e=>setFile(e.target.files?.[0]||null)} style={{padding:12,border:'1px solid #ccd2e3',borderRadius:10,flex:'1 1 300px'}}/><button disabled={busy} onClick={upload} style={{padding:'14px 24px',border:0,borderRadius:10,background:'#5b43ed',color:'white',fontWeight:800,fontSize:16}}>{busy?'Uploading…':'Upload securely'}</button></div>{msg&&<p style={{fontWeight:700,color:'#4d43a8'}}>{msg}</p>}</div>
 <div style={{marginTop:24}}><h2>Uploaded Documents ({docs.length})</h2>{docs.length===0?<div style={{background:'white',padding:30,borderRadius:16,border:'1px dashed #c9cfdf'}}>No documents uploaded yet.</div>:docs.map(d=><div key={d.id} style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:15,background:'white',padding:18,marginBottom:10,border:'1px solid #e0e4ef',borderRadius:14,flexWrap:'wrap'}}><div><b style={{fontSize:17}}>{d.file_name}</b><div style={{color:'#687086',marginTop:5}}>{d.category} · {Math.max(1,Math.round(Number(d.size_bytes||0)/1024))} KB</div></div><div style={{display:'flex',gap:8}}><button onClick={()=>download(d.id)} style={btn}>Download</button><button onClick={()=>remove(d.id)} style={{...btn,borderColor:'#e2b7bd'}}>Delete</button></div></div>)}</div></div></div>
}