'use client';
import {useMemo,useState} from 'react';
const opportunities=[
{type:'PhD',title:'AI & Medical Imaging PhD',org:'Global Research University',place:'International',funding:'Fully funded',deadline:'30 Nov 2026',match:92,tags:['AI','Medical Imaging','Research']},
{type:'Scholarship',title:'Global Postgraduate Scholarship',org:'International Scholarship Programme',place:'Multiple countries',funding:'Tuition + stipend',deadline:'15 Dec 2026',match:86,tags:['Masters','PhD','International']},
{type:'Fellowship',title:'Digital Health Research Fellowship',org:'Health Innovation Institute',place:'Hybrid',funding:'Funded fellowship',deadline:'10 Jan 2027',match:81,tags:['Digital Health','AI','Research']},
{type:'Job',title:'Medical Imaging AI Researcher',org:'Clinical AI Laboratory',place:'Remote / Hybrid',funding:'Salaried',deadline:'Rolling',match:78,tags:['Imaging','AI','Clinical']}
];
export default function Home(){const [q,setQ]=useState('');const [tab,setTab]=useState('Discover');const [saved,setSaved]=useState([]);const [profile,setProfile]=useState(35);const shown=useMemo(()=>opportunities.filter(x=>(x.title+x.org+x.type+x.tags.join(' ')).toLowerCase().includes(q.toLowerCase())),[q]);function save(i){setSaved(s=>s.includes(i)?s.filter(x=>x!==i):[...s,i])}
return <main><header><div className="brand"><span className="logo">A</span><b>ApplyAI</b></div><nav>{['Discover','Applications','Documents','Profile'].map(x=><button className={tab===x?'active':''} onClick={()=>setTab(x)} key={x}>{x}</button>)}</nav><button className="upgrade">Upgrade</button></header>
<section className="hero"><div className="eyebrow">YOUR OPPORTUNITY COPILOT</div><h1>Find it. <span>Qualify.</span> Apply.</h1><p>Discover scholarships, funded PhDs, fellowships and jobs. Check your eligibility against published requirements and prepare a stronger application from one workspace.</p><div className="search"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search PhDs, scholarships, jobs, fellowships…"/><button>Search opportunities</button></div><div className="chips"><span>Fully funded</span><span>International applicants</span><span>Remote</span><span>Medical & AI</span></div></section>
<section className="dashboard"><aside><div className="profile"><div className="ring">{profile}%</div><div><b>Complete your profile</b><p>Better profiles produce better eligibility checks.</p></div></div><button onClick={()=>setProfile(p=>Math.min(100,p+15))}>Continue profile →</button><hr/><h4>APPLICATION PIPELINE</h4><div className="stat"><b>{saved.length}</b><span>Saved</span></div><div className="stat"><b>0</b><span>Preparing</span></div><div className="stat"><b>0</b><span>Submitted</span></div><div className="notice"><b>🔔 Opportunity Watch</b><p>Get notified when new opportunities match your profile.</p><button>Set preferences</button></div></aside>
<div className="content"><div className="sectionTitle"><div><h2>Recommended opportunities</h2><p>Example opportunities for the MVP. Live official-source discovery is the next integration.</p></div><button>Filters ⚙</button></div><div className="cards">{shown.map((o,i)=><article key={o.title}><div className="cardtop"><span className={'type '+o.type.toLowerCase()}>{o.type}</span><button className="bookmark" onClick={()=>save(i)}>{saved.includes(i)?'★':'☆'}</button></div><h3>{o.title}</h3><p className="org">{o.org}</p><div className="meta"><span>⌖ {o.place}</span><span>◈ {o.funding}</span><span>◷ {o.deadline}</span></div><div className="tags">{o.tags.map(t=><span key={t}>{t}</span>)}</div><div className="match"><div><b>{o.match}%</b><small> profile match</small></div><div className="bar"><i style={{width:o.match+'%'}}/></div></div><div className="actions"><button>View requirements</button><button className="primary">Check eligibility</button></div></article>)}</div></div></section>
<section className="how"><div className="eyebrow">ONE PROFILE. MANY APPLICATIONS.</div><h2>From opportunity to submission</h2><div className="steps">{[['01','Build your profile','Upload your CV and add qualifications, experience, skills and preferences.'],['02','Discover','Find opportunities that fit your goals instead of searching dozens of sites.'],['03','Check eligibility','Compare your evidence against each published requirement and identify gaps.'],['04','Prepare','Create a checklist and tailored drafts for your review before submission.']].map(s=><div key={s[0]}><span>{s[0]}</span><h3>{s[1]}</h3><p>{s[2]}</p></div>)}</div></section><footer><b>ApplyAI</b><span>AI guidance should be verified against official opportunity requirements before submission.</span></footer></main>}
