'use client';
import {useEffect,useState} from 'react';
export default function SendApplicationBridge(){
 const[show,setShow]=useState(false),[confirming,setConfirming]=useState(false);
 useEffect(()=>{const sync=()=>{const text=document.body?.innerText||'';setShow(text.includes('Final Check')&&text.includes('Mark as Submitted'))};sync();const o=new MutationObserver(sync);o.observe(document.body,{childList:true,subtree:true,characterData:true});return()=>o.disconnect()},[]);
 function findButton(label){return [...document.querySelectorAll('button')].find(b=>b.textContent?.includes(label))}
 function save(){findButton('Save & Exit')?.click()}
 function continueToPortal(){setConfirming(false);const b=findButton('Open Official Application');if(b)b.click();else alert('The official application destination is not available for this vacancy yet. Your application remains saved in ApplyAI.')}
 function submitted(){findButton('Mark as Submitted')?.click()}
 if(!show)return null;
 return <><div style={{position:'fixed',right:24,bottom:24,zIndex:8000,width:330,background:'white',border:'1px solid #d9dff0',borderRadius:18,padding:18,boxShadow:'0 18px 50px #17214a30'}}><div style={{fontSize:12,fontWeight:900,letterSpacing:2,color:'#5b43ed'}}>FINAL APPLICATION</div><h3 style={{margin:'8px 0'}}>Ready to send?</h3><p style={{fontSize:13,color:'#667085',lineHeight:1.5}}>Save your work, review the clean application pack, then continue to the employer or university submission portal.</p><button onClick={()=>setConfirming(true)} style={{width:'100%',padding:'13px 16px',border:0,borderRadius:10,background:'#5b43ed',color:'white',fontWeight:900,fontSize:15}}>Send Application →</button><div style={{display:'flex',gap:8,marginTop:9}}><button onClick={save} style={{flex:1,padding:10,borderRadius:9,border:'1px solid #ccd2e3',background:'white',fontWeight:700}}>Save & Continue Later</button><button onClick={submitted} style={{flex:1,padding:10,borderRadius:9,border:'1px solid #ccd2e3',background:'white',fontWeight:700}}>Mark Submitted</button></div></div>{confirming&&<div style={{position:'fixed',inset:0,zIndex:9000,background:'#15182c88',display:'grid',placeItems:'center',padding:20}}><div style={{maxWidth:520,width:'100%',background:'white',borderRadius:20,padding:28,boxShadow:'0 24px 80px #0004'}}><div style={{fontSize:12,fontWeight:900,letterSpacing:2,color:'#5b43ed'}}>SEND APPLICATION</div><h2>Final submission</h2><p style={{color:'#596176',lineHeight:1.6}}>ApplyAI keeps your CV, cover letter and supporting documents in your workspace. Continue only after checking that your documents are complete and accurate.</p><div style={{background:'#f5f3ff',borderRadius:12,padding:14,margin:'16px 0'}}><b>$5 Application Pack</b><div style={{fontSize:13,marginTop:4}}>Unlock clean watermark-free CV and cover letter downloads.</div></div><div style={{background:'#f5f3ff',borderRadius:12,padding:14,margin:'10px 0 20px'}}><b>$12 Pro</b><div style={{fontSize:13,marginTop:4}}>Includes application workflow and up to 10 clean application packs per month.</div></div><button onClick={continueToPortal} style={{width:'100%',padding:14,border:0,borderRadius:10,background:'#5b43ed',color:'white',fontWeight:900}}>Continue to Official Application Portal →</button><button onClick={()=>setConfirming(false)} style={{width:'100%',padding:12,border:0,background:'transparent',marginTop:8,fontWeight:700}}>Back to Final Check</button><p style={{fontSize:12,color:'#7a8192'}}>Opening the official portal does not mark the application as submitted. Return to ApplyAI and use “Mark Submitted” after completing the employer/university submission.</p></div></div>}</>
}