import { db } from '../../../lib/db';
import { S3Client, PutObjectCommand, GetObjectCommand, DeleteObjectCommand } from '@aws-sdk/client-s3';
import { getSignedUrl } from '@aws-sdk/s3-request-presigner';
const BUCKET='applyai-documents';
function s3(){const endpoint=process.env.AWS_ENDPOINT_URL_S3;const accessKeyId=process.env.AWS_ACCESS_KEY_ID;const secretAccessKey=process.env.AWS_SECRET_ACCESS_KEY;if(!endpoint||!accessKeyId||!secretAccessKey)throw new Error('Document storage is not fully configured');return new S3Client({region:process.env.AWS_REGION||'eu-central-1',endpoint,forcePathStyle:true,credentials:{accessKeyId,secretAccessKey}})}
async function currentUser(request){const r=await fetch(new URL('/api/me',request.url),{headers:{cookie:request.headers.get('cookie')||'',accept:'application/json'},cache:'no-store'});if(!r.ok)return null;const d=await r.json().catch(()=>null);return d?.user||null}
async function ensure(sql){await sql`CREATE TABLE IF NOT EXISTS user_documents(id BIGSERIAL PRIMARY KEY,user_id TEXT NOT NULL,category TEXT NOT NULL,file_name TEXT NOT NULL,object_key TEXT NOT NULL UNIQUE,content_type TEXT,size_bytes BIGINT,created_at TIMESTAMPTZ NOT NULL DEFAULT now(),updated_at TIMESTAMPTZ NOT NULL DEFAULT now())`;await sql`CREATE INDEX IF NOT EXISTS user_documents_user_idx ON user_documents(user_id,updated_at DESC)`}
function safeName(n){return String(n||'document').replace(/[^a-zA-Z0-9._-]+/g,'_').slice(-160)}
export async function GET(request){try{const u=await currentUser(request);if(!u)return Response.json({error:'Sign in required'},{status:401});const sql=db();await ensure(sql);const rows=await sql`SELECT id,category,file_name,content_type,size_bytes,created_at,updated_at FROM user_documents WHERE user_id=${String(u.id)} ORDER BY updated_at DESC`;return Response.json({documents:rows},{headers:{'Cache-Control':'no-store'}})}catch(e){return Response.json({error:e.message},{status:500})}}
export async function POST(request){try{const u=await currentUser(request);if(!u)return Response.json({error:'Sign in required'},{status:401});const form=await request.formData();const file=form.get('file');const category=String(form.get('category')||'Supporting Document').slice(0,80);if(!file||typeof file.arrayBuffer!=='function')return Response.json({error:'Choose a file'},{status:400});if(file.size>15*1024*1024)return Response.json({error:'Maximum file size is 15 MB'},{status:400});const allowed=['application/pdf','application/msword','application/vnd.openxmlformats-officedocument.wordprocessingml.document','image/jpeg','image/png'];if(file.type&&!allowed.includes(file.type))return Response.json({error:'Use PDF, DOC, DOCX, JPG or PNG'},{status:400});const key=`users/${String(u.id).replace(/[^a-zA-Z0-9_-]/g,'_')}/${Date.now()}-${crypto.randomUUID()}-${safeName(file.name)}`;await s3().send(new PutObjectCommand({Bucket:BUCKET,Key:key,Body:Buffer.from(await file.arrayBuffer()),ContentType:file.type||'application/octet-stream'}));const sql=db();await ensure(sql);const rows=await sql`INSERT INTO user_documents(user_id,category,file_name,object_key,content_type,size_bytes) VALUES(${String(u.id)},${category},${file.name},${key},${file.type||null},${file.size}) RETURNING id,category,file_name,content_type,size_bytes,created_at,updated_at`;return Response.json({document:rows[0]})}catch(e){console.error('documents POST',e);return Response.json({error:e.message},{status:500})}}
export async function PATCH(request){try{const u=await currentUser(request);if(!u)return Response.json({error:'Sign in required'},{status:401});const b=await request.json();const sql=db();await ensure(sql);const rows=await sql`SELECT * FROM user_documents WHERE id=${b.id} AND user_id=${String(u.id)} LIMIT 1`;if(!rows[0])return Response.json({error:'Document not found'},{status:404});const url=await getSignedUrl(s3(),new GetObjectCommand({Bucket:BUCKET,Key:rows[0].object_key,ResponseContentDisposition:`attachment; filename="${safeName(rows[0].file_name)}"`}),{expiresIn:300});return Response.json({url})}catch(e){return Response.json({error:e.message},{status:500})}}
export async function DELETE(request){try{const u=await currentUser(request);if(!u)return Response.json({error:'Sign in required'},{status:401});const id=new URL(request.url).searchParams.get('id');const sql=db();await ensure(sql);const rows=await sql`SELECT * FROM user_documents WHERE id=${id} AND user_id=${String(u.id)} LIMIT 1`;if(!rows[0])return Response.json({error:'Document not found'},{status:404});await s3().send(new DeleteObjectCommand({Bucket:BUCKET,Key:rows[0].object_key}));await sql`DELETE FROM user_documents WHERE id=${id} AND user_id=${String(u.id)}`;return Response.json({ok:true})}catch(e){return Response.json({error:e.message},{status:500})}}
