import { NextResponse } from 'next/server';
import { db } from '../../../lib/db';
import { normalizeOpportunity, isUsable } from '../../../lib/opportunity-engine';

const TRUSTED_HOSTS=['.gov','.gov.uk','.gov.au','.govt.nz','.gc.ca','.edu','.ac.uk','.edu.au','.ac.nz','.ac.za','.edu.hk','.edu.sg','.edu.my','.europa.eu','jobs.nhs.uk','healthjobsuk.com','euraxess.ec.europa.eu','academicpositions.com','findaphd.com','daad.de','jobs.lever.co','boards.greenhouse.io'];
const ADZUNA_COUNTRIES=['gb','us','ca','au','nz','de','fr','nl','sg','za','in','br','pl','at'];
function trusted(url=''){try{const h=new URL(url).hostname.toLowerCase();return TRUSTED_HOSTS.some(x=>x.startsWith('.')?h.endsWith(x):h===x||h.endsWith('.'+x));}catch{return false}}
async function searchAdzuna(q){if(!q||!process.env.ADZUNA_APP_ID||!process.env.ADZUNA_APP_KEY)return[];const searches=ADZUNA_COUNTRIES.map(async country=>{try{const u=new URL(`https://api.adzuna.com/v1/api/jobs/${country}/search/1`);u.searchParams.set('app_id',process.env.ADZUNA_APP_ID);u.searchParams.set('app_key',process.env.ADZUNA_APP_KEY);u.searchParams.set('results_per_page','20');u.searchParams.set('what',q);u.searchParams.set('content-type','application/json');const r=await fetch(u,{cache:'no-store'});if(!r.ok)return[];const d=await r.json();return(d.results||[]).map(raw=>normalizeOpportunity({...raw,type:'Job',source_name:'Adzuna',source_url:raw.redirect_url,country})).filter(isUsable)}catch{return[]}});return(await Promise.all(searches)).flat().slice(0,100)}
function researchLinks(q){const s=q.toLowerCase();if(!/(phd|doctoral|doctorate|research|fellow|fellowship|scholarship|studentship|postdoc|postdoctoral|funded)/.test(s))return[];const encoded=encodeURIComponent(q);return[{id:'research-euraxess',type:'Research',title:`Search EURAXESS for ${q}`,organization:'EURAXESS — European Commission',location:'Europe and international',funding:'Funding varies — verify listing',deadline:null,source_url:`https://euraxess.ec.europa.eu/jobs/search?keywords=${encoded}`,source_name:'EURAXESS',is_verified:true,requirements:'Live research jobs, PhD positions, fellowships, funding and hosting opportunities.'},{id:'research-daad',type:'Scholarship',title:`Search DAAD opportunities for ${q}`,organization:'German Academic Exchange Service (DAAD)',location:'Germany / international',funding:'Scholarship/funding varies',deadline:null,source_url:'https://www.daad.de/en/studying-in-germany/scholarships/',source_name:'DAAD',is_verified:true,requirements:'Official scholarship and funding discovery.'}];}
export async function GET(request){try{const sql=db();const{searchParams}=new URL(request.url);const q=(searchParams.get('q')||'').trim();const rows=q?await sql`SELECT id,type,title,organization,location,funding,deadline,source_url,source_name,is_verified,requirements FROM opportunities WHERE is_verified=true AND (deadline IS NULL OR deadline>=CURRENT_DATE) AND (title ILIKE ${'%'+q+'%'} OR organization ILIKE ${'%'+q+'%'} OR type ILIKE ${'%'+q+'%'} OR requirements ILIKE ${'%'+q+'%'}) ORDER BY deadline NULLS LAST LIMIT 100`:await sql`SELECT id,type,title,organization,location,funding,deadline,source_url,source_name,is_verified,requirements FROM opportunities WHERE is_verified=true AND (deadline IS NULL OR deadline>=CURRENT_DATE) ORDER BY deadline NULLS LAST LIMIT 100`;const verified=rows.filter(x=>trusted(x.source_url));if(!q)return NextResponse.json({opportunities:verified,source:'ApplyAI verified catalogue'});const[live,research]=await Promise.all([searchAdzuna(q),Promise.resolve(researchLinks(q))]);const combined=[...verified];const seen=new Set(verified.map(x=>`${String(x.title).toLowerCase()}|${String(x.organization).toLowerCase()}`));for(const x of[...live,...research]){const k=`${String(x.title).toLowerCase()}|${String(x.organization).toLowerCase()}`;if(seen.has(k))continue;seen.add(k);combined.push({...x,id:x.id||`live-${countrySafe(x.source_url)}-${combined.length}`,is_verified:true})}return NextResponse.json({opportunities:combined.slice(0,100),source:'ApplyAI global verified discovery',live_count:live.length,research_count:research.length})}catch(e){return NextResponse.json({opportunities:[],error:'Unable to load opportunities',detail:String(e?.message||e)},{status:500})}}
function countrySafe(s=''){let h=0;for(let i=0;i<s.length;i++)h=(h*31+s.charCodeAt(i))>>>0;return h.toString(36)}
